# Generated by Django 3.2.13 on 2022-04-29 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import invmanager.models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Last changes')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Company name')),
                ('email', models.EmailField(blank=True, max_length=150, verbose_name='E-Mail')),
                ('is_craft_enterprise', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Last changes')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('inspection_interval', models.IntegerField(blank=True, verbose_name='Inspection interval')),
                ('last_inspection_date', models.DateField(blank=True, verbose_name='Last inspection')),
                ('additional_information', models.TextField(blank=True, verbose_name='Additional information')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Last changes')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('street', models.CharField(blank=True, max_length=150, verbose_name='Street')),
                ('house_number', models.CharField(blank=True, max_length=150, verbose_name='House number')),
                ('postal_code', models.CharField(blank=True, max_length=150, verbose_name='Postal code')),
                ('city', models.CharField(max_length=150, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=150, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='MachineryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Last changes')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('type', models.CharField(max_length=150, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Last changes')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('maintenance_interval', models.IntegerField(blank=True, verbose_name='Maintenance interval')),
                ('last_maintenance_date', models.DateField(blank=True, verbose_name='Last maintenance')),
                ('additional_information', models.TextField(blank=True, verbose_name='Additional information')),
            ],
        ),
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Last changes')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('machinery_name', models.CharField(blank=True, max_length=150, verbose_name='Name')),
                ('machinery_number', models.IntegerField(max_length=150, verbose_name='Number')),
                ('date_of_installation', models.DateField(blank=True, verbose_name='Date of installation')),
                ('replacement_interval', models.IntegerField(blank=True, verbose_name='Replacement time')),
                ('company', models.ForeignKey(on_delete=invmanager.models.Company, to='invmanager.company')),
                ('inspection', models.ForeignKey(on_delete=invmanager.models.Inspection, to='invmanager.inspection')),
                ('location', models.ForeignKey(on_delete=invmanager.models.Location, to='invmanager.location')),
                ('machinery_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invmanager.machinerytype')),
                ('maintenance', models.ForeignKey(on_delete=invmanager.models.Maintenance, to='invmanager.maintenance')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Last changes')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('product_number', models.CharField(max_length=100, verbose_name='Product number')),
                ('description', tinymce.models.HTMLField(blank=True, max_length=500, verbose_name='Description')),
                ('company', models.ForeignKey(on_delete=invmanager.models.Company, to='invmanager.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Last changes')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('last_name', models.CharField(max_length=150, verbose_name='First name')),
                ('first_name', models.CharField(max_length=150, verbose_name='Last name')),
                ('email', models.EmailField(blank=True, max_length=150, verbose_name='E-Mail')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=invmanager.models.Company, to='invmanager.company')),
                ('machinery', models.ManyToManyField(blank=True, to='invmanager.Machinery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (),
            },
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.ManyToManyField(to='invmanager.Location'),
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.ManyToManyField(blank=True, to='invmanager.MachineryType'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
