# Generated by Django 3.2.13 on 2022-05-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invmanager', '0002_auto_20220429_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinery',
            old_name='machinery_name',
            new_name='name',
        ),
    ]
